import Footer from "../_components/Footer";
import "./auth.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="false">
        {children}
        <Footer />
      </body>
    </html>
  );
}
