"use client";
import Link from "next/link";
import Footer from "../_components/Footer";
import "./auth.css";
import { usePathname } from "next/navigation";
import { useState } from "react";

/* export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

const navLinks = [
  {
    name: "Register",
    href: "/register",
  },
  {
    name: "Login",
    href: "/login",
  },
  {
    name: "Forgot Password",
    href: "/forgotPassword",
  },
];

export default function AuthLayout({ children }) {
  const pathName = usePathname();
  const [name, setName] = useState("");
  return (
    <html lang="en">
      <body cz-shortcut-listen="false">
        <input
          type="text"
          value={name}
          onChange={(e) => setName(e.target.value)}
          className="border border-white"
        />
        <ul>
          {navLinks.map((link) => {
            const isActive =
              pathName === link.href ||
              (pathName.startsWith(link.href) && link.href !== "/");
            return (
              <li
                key={link.href}
                className={
                  isActive
                    ? "text-3xl font-bold text-purple-800"
                    : "text-xl text-white"
                }
              >
                <Link href={link.href}>{link.name}</Link>
              </li>
            );
          })}
        </ul>
        {children}
        <Footer />
      </body>
    </html>
  );
}
