import Footer from "../_components/Footer";
import Header from "../_components/Header";
import "./globals.css";

export const metadata = {
  title: "Learning Next.js",
  description: "Generated by create next app",
};

export default function RemainingLayout({ children }) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="false">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
